baseURL = "https://sleepy-morse-8edf67.netlify.com"
languageCode = "en-us"
title = "Jennifer Johnson"

[author]
name = "Jennifer Johnson"

[params]
mainSections = ["posts"]
favicon = "/img/woman-technologist.png"
# favicon = "/img/star.png"

[[params.socials]]
link = "/"
name = "Writing"
[[params.socials]]
link = "/about"
name = "About Me"
[[params.socials]]
link = "https://github.com/jkerr321"
name = "Github"

